### ISSUE TITLE
Unit for the output value.

### ISSUE THREAD

**Issue by ronakdedhia18** [avaldebe/AQmon#9]
Hi,
I am getting readings like this for PMS7003 sensor : 

Date_Time                 | PM1 | PM2.5 | PM10
2019/02/13 12:52:09 | 386 | 1142 | 1267

Can anyone please tell me what will be the units of this.
Is the ug/m3 or total count of paarticles at that moment?

Thank you.

**Comment by avaldebe** [comment]
Are you using the lua module to read the PMS7003?
I do not recognize the output format.

I wrote this proyect long time ago, before we had Arduino for the esp8266,
and I only tested it on the PMS3003 sensor. Since then I wrote [PMserial](https://github.com/avaldebe/PMserial), a generic Arduino library
for the PMSx003 sensors. Maybe you should try that instead of this old/stale modules.

The messages from the PMS7003 are longer than the messages from the PMS3003 (32 bytes vs 24 bytes). Therefore you need the right sensor type on the [module configuration](https://github.com/avaldebe/AQmon/blob/master/lua_modules/pms3003.lua#L36)

You can find the message description [here](https://github.com/avaldebe/AQmon/blob/master/lua_modules/pms3003.lua#L49-L85).

The PM1, PM2.5 and PM10 parts of the message are on ug/m3 and the particle count in number/100cc,
see [here](https://github.com/avaldebe/AQmon/blob/master/lua_modules/pms3003.lua#L20-L31).

Where are you located? Those values are way too high for Europe, unless you're measuring next to an open fire place or on a kitchen next to a frying pan.

If you are getting high fluctuation on the values, it could be that you are missing the beginning of the message.

**Comment by ronakdedhia18** [comment]
Hi Alvaro,
I am using my own python code with Raspberry Pi for getting values from PMS7003.
I am based in India and this readings are from my bedroom at room temperature.
Ill send my code can you please run and check if i am doing it correct?
Thankyou in advance.

[New folder.zip](https://github.com/avaldebe/AQmon/files/2873974/New.folder.zip)

**Comment by avaldebe** [comment]
Can I see the full output of your script?

In the meantime, it looks like your checksum calculation is wrong:
```python
            # Calculate the payload checksum (not including the payload checksum bytes)
            inputChecksum = 0x42 + 0x4d
            for x in range(0, 27):
                inputChecksum = inputChecksum + data[x]
```
Here, `range(0, 27)` will only give you the first 27 indexes (`[0, 1, ..., 26]`).
You need the first 28 indexes, as the last 2 are the checksum.
Instead you can write the checksum calculation as:
```python
            # Calculate the payload checksum (not including the payload checksum bytes)
            inputChecksum = 0x42 + 0x4d + sum(data[:-2])
```

BTW, if you do not want to create a full repository for your script,
you can [create a gist](https://gist.github.com/).
That would make easy to comment on the particular lines...

**Comment by ronakdedhia18** [comment]
Hi Alvaro,
Below is the output of my script : 
PMS7003 Sensor Data:
PM1.0 = 104 ug/m3
PM2.5 = 163 ug/m3
PM10 = 176 ug/m3
PM1 Atmospheric concentration = 69 ug/m3
PM2.5 Atmospheric concentration = 108 ug/m3
PM10 Atmospheric concentration = 117 ug/m3
Count: 0.3um = 18084 per 0.1l
Count: 0.5um = 5227 per 0.1l
Count: 1.0um = 1020 per 0.1l
Count: 2.5um = 90 per 0.1l
Count: 5.0um = 20 per 0.1l
Count: 10um = 6 per 0.1l
Version = 151
Error Code = 0
Frame length = 28

Let me know if i am still wrong in calculation.
And sorry i am in little rush so not creating gist as of now.
Need to get this sensor up and running for my project.
Thank you.

**Comment by avaldebe** [comment]
The output looks right. Remeber to use the "Atmospheric concentration" version of the PM values.

**Comment by ronakdedhia18** [comment]
Hi Alvaro,
Can you please try this code out and check your output as well because i am confused right now after you said that i have did wrong calculations.
Please let me know.

Thank you.

**Comment by avaldebe** [comment]
I wont test and debug your code. This is not stack overflow, it is the issue tracker for a project that you are not using.

What I said is that the checksum calculation looks wrong. The checksum will tell you if you revived the message correctly or not.  You can decide yourself if my assessment about your checksum calculation correct or not. For example, if every message you read and decode triggers a checkum warning, it is quite likely your checksum code is wrong.

**Comment by ronakdedhia18** [comment]
No problem.
Thank you for all your help.
